name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: rohitkumarrai7
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to output branch
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout -b output 2>/dev/null || git checkout output
          cp dist/github-contribution-grid-snake.svg .
          git add .
          git commit -m "Generate snake animation" --allow-empty
          git push origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
